### ISSUE TITLE
Any plans to expand support?

### ISSUE THREAD

**Issue by schrepfler** [maxhgerlach/tensorflow-1.8.0-ubuntu16.04-py27-no_avx-xeon_x5650#1]
Would be nice to provide more builds for CUDA 9.0 + cuDNN 7

| version  | cpu/gpu | python |
| ------- | ----- | -------- |
| 1.8.0  | cpu  | py27  |
| 1.8.0  | cpu  | py3x  |
| 1.8.0  | gpu  | py27  |
| 1.8.0  | gpu  | py3x  |
| 1.9.0  | cpu  | py27  |
| 1.9.0  | cpu  | py3x  |
| 1.9.0  | gpu  | py27  |
| 1.9.0  | gpu  | py3x  |

**Comment by maxhgerlach** [comment]
Sorry, just sharing what I built for my own needs.

Check out https://github.com/yaroslavvb/tensorflow-community-wheels for more options.
